<?php
    require_once("../core/PDOManager.class.php");
    require_once("PDOUrlManager.class.php");

    require_once("../model/User.class.php");

    session_start();
    if(!isset($_SESSION['user'])){
        header('Location: /suplink/view/');
    }else{
        $user = $_SESSION['user'];
    }


    $PDOmanager = new PDOManager;
    $pdo = $PDOmanager->instantiatePdo();


    if(isset($_GET['shortUrl'])){
        $shortUrl= $_GET['shortUrl'];
    }else{
        header("Location:/suplink/view");
    }

// We get the number of clicks and the id of the shortUrl put in the request : localhost/suplink/xxxxx
    $query=$pdo->prepare('SELECT click, id FROM urls WHERE shortUrl = :shortUrl && userId = :userId');
    $query->execute(array(
        ':shortUrl' => $shortUrl,
        ':userId' => $user->getId()
    ));



    $data = $query->fetch(PDO::FETCH_ASSOC);
// If there is data we extract it and we can process it afterwards, otherwise, we redirect to the homePage
// ( it may mean that the url exists but wasn't generated by the actual user logged in)
    if($data){
        $click = $data["click"];
        $urlId = $data["id"];
    }else{
        header("Location:/suplink/view");
    }

// Now we are sure that the url exist and that it is associated to the proper user.
// So we have to check if the url is ENABLED or DISABLED
    $sql=$pdo->prepare('SELECT * FROM urls WHERE id = :urlId && shortUrl= :shortUrl && active = 1 ');
    $sql->execute(array(
        ':urlId' => $urlId,
        ':shortUrl' => $shortUrl
    ));


// if the url is enabled then we INCREMENT the number of clicks AND update the urls table.
// if not, we redirect to the index page.
    $data = $sql->fetch(PDO::FETCH_ASSOC);
    if($data){
        $click++;
        $url=$data['url'];
        $sql=$pdo->prepare('UPDATE urls SET click= :click WHERE shortUrl = :shortUrl');
        $sql->execute(array(
            ':click' => $click,
            ':shortUrl' => $shortUrl
        ));
        header("location:".$url);

    }else{
        header("location:/suplink/view");
    }









?>